name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      make_release:
        description: 'Create a GitHub Release with APK'
        required: false
        type: boolean
        default: false
      tag_name:
        description: 'Release tag (used when make_release=true)'
        required: false
      release_name:
        description: 'Release name (used when make_release=true)'
        required: false
      prerelease:
        description: 'Mark release as prerelease'
        required: false
        type: boolean
        default: true
  push:
    paths:
      - 'android-stt/**'
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      - name: Build debug APK (Gradle 8.7)
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7
          build-root-directory: android-stt
          arguments: :app:assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: elder-stt-debug-apk
          path: android-stt/app/build/outputs/apk/debug/app-debug.apk

      - name: Create GitHub Release from tag
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: android-stt/app/build/outputs/apk/debug/app-debug.apk
          name: Elder STT ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Create GitHub Release (manual)
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.make_release }}
        uses: softprops/action-gh-release@v1
        with:
          files: android-stt/app/build/outputs/apk/debug/app-debug.apk
          tag_name: ${{ inputs.tag_name != '' && inputs.tag_name || format('debug-{0}', github.run_number) }}
          name: ${{ inputs.release_name != '' && inputs.release_name || format('Elder STT Debug Build #{0}', github.run_number) }}
          draft: false
          prerelease: ${{ inputs.prerelease }}
